AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Project to create a Lambda that converts phone numbers and saves the 5 best
  resulting words from that number into Amazon's DynamoDB. Part of the assignment
  also was to create an Amazon Connect contact flow that reviews a caller's phone
  number and provides 3 vanity possibilities that are returned.
Resources:
  myDynamoDBTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      -
        AttributeName: "PhoneNumberResults"
        AttributeType: "S"
    KeySchema:
      -
        AttributeName: "PhoneNumberResults"
        KeyType: "HASH"
    TableName:
