AWSTemplateFormatVersion: "2010-09-09"
Description: |
  Project to create a Lambda that converts phone numbers and saves the 5 best
  resulting words from that number into Amazon's DynamoDB. Part of the assignment
  also was to create an Amazon Connect contact flow that reviews a caller's phone
  number and provides 3 vanity possibilities that are returned.
Resources:
  myDynamoDBTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      -
        AttributeName: "ID"
        AttributeType: "S"
      -
        AttributeName: "PhoneNumberResults"
        AttributeType: "S"
    KeySchema:
      -
        AttributeName: "ID"
        KeyType: "HASH"
      -
        AttributeName: "PhoneNumberResults"
        KeyType: "HASH"
    TableName: &dataBaseTableName "VanityNumbers"
    awsLambdaDynamoDbRole:
      Type: AWS::IAM::Role
      Properties:
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action:
                - 'sts:AssumeRole'
              Path: /
              ManagedPolicyArns:
                - ["arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole"]
              MaxSessionDuration: 4000
              RoleName: AWS_VanityNumber_Lambda
              Policies:
                - PolicyName: AWS_VanityNum_Lambda_DynamoDB_Permission
